Repository morsby/medmcq, pull requests merged in 2019-08, with the labels that each got.

#375 Added share builder
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/actions/question.ts
  client/src/apolloClient.ts
  client/src/components/Layout/Footer.js
  client/src/components/Layout/layoutTranslations.json
  client/src/components/Quiz/Question/QuestionMetadata/QuestionMetadataDropdown.jsx
  client/src/components/Quiz/QuizShareBuilderLoader.tsx
  client/src/components/Quiz/QuizShareRoute.tsx
  client/src/containers/ShareBuilder.css
  client/src/containers/Sharebuilder.tsx
  client/src/index.tsx
  client/src/pages/Selection.jsx
  client/src/queries/shareLink.ts
  server/__tests__/routes/questions/sharebuilder.test.ts
  server/graphql/apolloServer.ts
  server/graphql/schema.ts
  server/graphql/types/shareLink.ts
  server/migrations/20190729161919_create_share_links.js
  server/models/shareLink.ts
  server/package-lock.json
  server/package.json
  server/server.ts
Labels: enhancement

#376 Advanced share builder
  .eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.tsx
  client/src/actions/index.js
  client/src/actions/shareBuilder.ts
  client/src/actions/types.js
  client/src/apolloClient.ts
  client/src/components/Sharebuilder/extendedRow.tsx
  client/src/components/Sharebuilder/searchDropdown.tsx
  client/src/containers/Sharebuilder.tsx
  client/src/index.tsx
  client/src/pages/ShareBuilder.css
  client/src/pages/Sharebuilder.tsx
  client/src/queries/questions.ts
  client/src/queries/shareLink.ts
  client/src/reducers/index.ts
  client/src/reducers/shareBuilderReducer.ts
  client/src/version.js
  package-lock.json
  package.json
  server/__tests__/routes/questions/sharebuilder.test.ts
  server/graphql/schema.ts
  server/graphql/types/question.ts
  server/graphql/types/shareLink.ts
  server/jest.config.js
  server/models/question.ts
  server/nodemon.json
  server/package-lock.json
  server/package.json
  server/tsconfig.json
Labels: big-project, enhancement

#383 Tags search + alphabetic sort of tags
  client/src/Translations/selectionTranslations.json
  client/src/components/SelectionSettings/SelectionMetadataSelector/SelectionMetadataSelector.tsx
Labels: enhancement

#384 Examset question uploader
  client/public/images/Abd-2019-F-36.jpg
  client/public/images/Abd-2019-F-37.jpg
  client/public/images/HLK-2019-F-1.jpg
  client/public/images/HLK-2019-F-15.jpg
  client/public/images/HLK-2019-F-19.jpg
  client/public/images/HLK-2019-F-21.jpg
  client/public/images/HLK-2019-F-25.jpg
  client/public/images/HLK-2019-F-26.jpg
  client/public/images/HLK-2019-F-31.jpg
  client/public/images/HLK-2019-F-33.jpg
  client/public/images/HLK-2019-F-34.jpg
  client/public/images/HLK-2019-F-35.jpg
  client/public/images/HLK-2019-F-43.jpg
  client/public/images/HLK-2019-F-49.jpg
  client/public/images/HLK-2019-F-50.jpg
  client/public/images/HLK-2019-F-51.jpg
  client/public/images/HLK-2019-F-64.jpg
  client/public/images/HLK-2019-F-65.jpg
  client/public/images/HLK-2019-F-67.jpg
  client/public/images/HLK-2019-F-69.jpg
  client/public/images/HLK-2019-F-70.jpg
  client/public/images/HLK-2019-F-73.jpg
  client/public/images/HLK-2019-F-78.jpg
  client/public/images/Inf-2019-F-1.jpg
  client/public/images/Inf-2019-F-2.jpg
  client/public/images/Inf-2019-F-3.jpg
  client/public/images/Inf-2019-F-36.jpg
  server/middleware/logger.ts
  server/routes/exam_sets.js
Labels: high priority
